services:

  api1-147ai:
    build: .
    # image: calciumion/new-api:latest
    container_name: api1-147ai
    restart: always
    command: --log-dir /app/logs
    ports:
      - "5000:3000"
    volumes:
      - ./api1/data:/data
      - ./api1/logs:/app/logs
    environment:
      - SQL_DSN=adminadmin:Zwq_13422482866@tcp(rm-rj98d1fq8l297e96ldo.mysql.rds.aliyuncs.com:3306)/new_api_147api_1
      - TZ=Asia/Shanghai
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
